config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# 顧客用
# URL /customers/sign_in ...
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


root to: "homes#top"
scope module: :public do
    resources :books, only: [:new, :index, :show, :edit, :create, :update] do
        resource :favorites, only: [:create, :destroy]
        resources :book_comments, only: [:create]
    end
    resources :users, omly: [:show, :edit, :update] do
       resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
        end
    end
    get 'screens/screen'
    get 'searches/search'
    get 'screens/guest'
end

namespace :admin do
   resources :books do
     resources :comments, only: [:index]
    end
  get 'screens/screen'
  resources :users, only: [:index, :show]
end
 post '/homes/guest_sign_in', to: 'homes#new_guest'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  validates :title, presence: true
  validates :author, presence: true

  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User" #フォローするユーザーのid
  belongs_to :followed, class_name: "User" #フォローされるユーザーのid
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :book_tags, dependent: :destroy
  has_many :books, through: :book_tags, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  with_options presence: true do
   validates :name
   validates :email
 end

 # 自分がフォローされる（被フォロー）側の関係性
 # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 # @user.booksのように、@user.yyyで、そのユーザがフォローしている人orフォローされている人の一覧を出したい
 # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

 #自分がフォローする側の可能性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
 #与フォローの関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

# フォローしたときの処理
def follow(user)
  relationships.create(followed_id: user.id)
end
# フォローを外すときの処理
def unfollow(user)
  relationships.find_by(followed_id: user.id).destroy
end
def following?(user)
  followings.include?(user)
end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController

  def index
    @books = Book.all
  end


  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

    private

  def book_params
    params.require(:book).permit(:memo, :title, :comment, :author, :publisher)
  end
end

app/controllers/admin/screens_controller.rb
class Admin::ScreensController < ApplicationController
  def screen

  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
     @user = User.find(params[:id])
     @books = @user.books
  end


 def index
   @users = User.all
 end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    screens_screen_path
  end


  def after_sign_out_path_for(resource)
    root_path
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:introduction])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end


  def new_guest
    user = User.find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to screens_guest_path, notice: 'ゲストユーザーとしてログインしました'
  end

end

app/helpers/admin/book_comments_helper.rb
module Admin::BookCommentsHelper
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/screens_helper.rb
module Admin::ScreensHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
<div class="search_form">
  <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKCATALOG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<body>
  <header>
    <% if user_signed_in? %>
        <%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
        <%= button_to "ホーム", screens_screen_path, method: :get, class: "btn btn-outline-secondary" %>

         <div class="search_form">
          <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['User'], ['Book']]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn-sm btn-primary" %>
          <% end %>
         </div>

    <% elsif admin_signed_in? %>
         <%= button_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %>
         <%= button_to "管理者側のホームへ戻る", admin_screens_screen_path, method: :get, class: "btn btn-outline-secondary" %>
    <% else %>
        <%= button_to "新規登録", new_user_registration_path, method: :get, class: "btn btn-outline-secondary" %>
        <%= button_to "ログイン", new_user_session_path, method: :get, class: "btn btn-outline-secondary" %>
        <%= button_to "TOPへ戻る", root_path, method: :get, class: "btn btn-outline-secondary" %>
    <% end %>
  </header>
    <%= yield %>
</body>
</html>